/* ============================================================
   Star Readers — CHESS (A+ UIL Chess Puzzle practice)
   Multiple-choice puzzles on board diagrams, split into the
   contest's three divisions. Every answer has been checked by
   hand. Squares use algebraic notation (files a-h, ranks 1-8).
   Piece codes: "wN" = white knight, "bP" = black pawn, etc.
     div: "23" (grades 2-3), "45" (grades 4-5), "68" (grades 6-8)
   Add your own by copying an entry and giving it a div.
   ============================================================ */
const CHESS_DIVISIONS = [
  { id: "23", label: "Grades 2–3", emoji: "🐣" },
  { id: "45", label: "Grades 4–5", emoji: "⭐" },
  { id: "68", label: "Grades 6–8", emoji: "🔥" },
];

const CHESS_PUZZLES = [
  /* ---------------- Grades 2–3 ---------------- */
  { div: "23", board: { e4: "wN" }, highlight: ["e4"],
    ask: "What is this white chess piece?",
    options: ["Knight", "Bishop", "Rook"], answer: "Knight",
    tip: "The piece shaped like a horse is the Knight." },
  { div: "23", board: { d5: "wR" }, highlight: ["d5"],
    ask: "What is this white chess piece?",
    options: ["Rook", "Queen", "Pawn"], answer: "Rook",
    tip: "The piece that looks like a castle tower is the Rook." },
  { div: "23", board: { c4: "wB" }, highlight: ["c4"],
    ask: "What is this white chess piece?",
    options: ["Bishop", "Knight", "King"], answer: "Bishop",
    tip: "The Bishop has a tall hat with a slit on top." },
  { div: "23", board: { d1: "wQ" }, highlight: ["d1"],
    ask: "What is this white chess piece?",
    options: ["Queen", "King", "Rook"], answer: "Queen",
    tip: "The Queen wears a pointed crown. She is the strongest piece." },
  { div: "23", board: { e1: "wK" }, highlight: ["e1"],
    ask: "What is this white chess piece?",
    options: ["King", "Queen", "Pawn"], answer: "King",
    tip: "The King wears a crown with a cross on top. Keep him safe!" },
  { div: "23", board: { d2: "wP" }, highlight: ["d2"],
    ask: "Which square is the pawn on? (file letter, then rank number)",
    options: ["d2", "d4", "b2"], answer: "d2",
    tip: "Read the file letter (d) first, then the rank number (2)." },
  { div: "23", board: { f6: "bN" }, highlight: ["f6"],
    ask: "Which square is the black knight on?",
    options: ["f6", "f3", "h6"], answer: "f6",
    tip: "File f, rank 6 → f6." },
  { div: "23", board: { d1: "wQ" }, highlight: ["d1"],
    ask: "How many points is the Queen worth?",
    options: ["9", "5", "3"], answer: "9",
    tip: "Values: Pawn 1, Knight 3, Bishop 3, Rook 5, Queen 9." },
  { div: "23", board: { a2: "wP" }, highlight: ["a2"],
    ask: "How many points is a Pawn worth?",
    options: ["1", "3", "5"], answer: "1",
    tip: "A pawn is worth 1 point." },
  { div: "23", board: { a1: "wR", g1: "wN" }, highlight: ["a1", "g1"],
    ask: "Which is worth more — a Rook or a Knight?",
    options: ["Rook", "Knight", "Same"], answer: "Rook",
    tip: "A Rook (5) is worth more than a Knight (3)." },
  { div: "23", board: { a2: "wP", b2: "wP", c2: "wP" }, highlight: [],
    ask: "How many white pawns are on the board?",
    options: ["3", "2", "4"], answer: "3",
    tip: "Count them: a2, b2, c2 = 3 pawns." },
  { div: "23", board: { d4: "wR" }, highlight: ["d4"],
    ask: "Which piece moves only in straight lines (never diagonally)?",
    options: ["Rook", "Bishop", "Pawn"], answer: "Rook",
    tip: "Rooks move straight; bishops move diagonally." },
  { div: "23", board: { g1: "wN" }, highlight: ["g1"],
    ask: "A knight can jump over other pieces. True or false?",
    options: ["True", "False"], answer: "True",
    tip: "The knight is the only piece that can jump over others." },
  { div: "23", board: { e1: "wK", e8: "bK" }, highlight: [],
    ask: "Which color moves first in a chess game?",
    options: ["White", "Black"], answer: "White",
    tip: "White always moves first." },

  /* ---------------- Grades 4–5 ---------------- */
  { div: "45", board: { d4: "wN" }, highlight: ["d4"],
    ask: "The knight is on d4. Which square can it jump to?",
    options: ["f5", "e5", "d6"], answer: "f5",
    tip: "A knight moves in an L: two squares, then one to the side (d4 → f5)." },
  { div: "45", board: { c1: "wB" }, highlight: ["c1"],
    ask: "Which square can this bishop reach?",
    options: ["a3", "c3", "d1"], answer: "a3",
    tip: "Bishops move diagonally: c1 → b2 → a3." },
  { div: "45", board: { a1: "wR", a6: "bP" }, highlight: ["a1", "a6"],
    ask: "Can the white Rook capture the black pawn?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "The a-file is open, so the rook slides up and captures." },
  { div: "45", board: { e8: "bK", e1: "wR" }, highlight: ["e8", "e1"],
    ask: "Is the black King in check?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "The rook attacks up the open e-file to the king — that is check." },
  { div: "45", board: { e4: "wP", d5: "bP" }, highlight: ["e4", "d5"],
    ask: "Can the white pawn on e4 capture the black pawn on d5?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "Pawns capture diagonally forward: e4 takes d5." },
  { div: "45", board: { e4: "wP", e5: "bP" }, highlight: ["e4", "e5"],
    ask: "Can the white pawn on e4 capture the black pawn right in front on e5?",
    options: ["No", "Yes"], answer: "No",
    tip: "Pawns capture diagonally, never straight ahead." },
  { div: "45", board: { e5: "wP", d5: "bP" }, highlight: ["e5", "d5"],
    ask: "Black's pawn just moved d7 → d5. Can the white e5 pawn capture 'en passant'?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "En passant: right after a two-square pawn jump, a pawn beside it can capture to the square behind (d6)." },
  { div: "45", board: { d1: "wQ" }, highlight: ["d1"],
    ask: "The Queen can move like which two pieces combined?",
    options: ["Rook and Bishop", "Knight and King", "Two Rooks"], answer: "Rook and Bishop",
    tip: "The Queen moves in straight lines AND diagonals." },
  { div: "45", board: { d1: "wR", d8: "bQ" }, highlight: ["d1", "d8"],
    ask: "The d-file is open. Can the white Rook win the black Queen?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "Rxd8 slides up the open file and captures the queen — winning material!" },
  { div: "45", board: { h8: "bK", h7: "bP", g7: "bP", a8: "wR" }, highlight: ["h8", "a8"],
    ask: "Black King is on h8. Is this checkmate?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "The rook checks along rank 8 and the king's own pawns block its escape — a back-rank mate." },
  { div: "45", board: { c5: "bK" }, highlight: [],
    ask: "No legal move, and the king is NOT in check. What is this called?",
    options: ["Stalemate", "Checkmate", "Check"], answer: "Stalemate",
    tip: "Stalemate is a draw — nobody wins." },
  { div: "45", board: { g1: "wN" }, highlight: ["g1"],
    ask: "The knight moves g1 → f3, written “Nf3”. What does the N stand for?",
    options: ["Knight", "Night", "Nothing"], answer: "Knight",
    tip: "N = Knight (K is already used for the King)." },
  { div: "45", board: { e1: "wK" }, highlight: ["e1"],
    ask: "When the king castles, how many squares does the king move?",
    options: ["2", "1", "3"], answer: "2",
    tip: "In castling the king moves two squares toward the rook." },

  /* ---------------- Grades 6–8 ---------------- */
  { div: "68", board: { h8: "bK", g7: "bP", h7: "bP", a1: "wR" }, highlight: ["h8", "a1"],
    ask: "White to move. Which move is checkmate?",
    options: ["Ra8 (rook to a8)", "Rh1 (rook to h1)", "Rb1 (rook to b1)"], answer: "Ra8 (rook to a8)",
    tip: "Ra8 checks along the back rank; the king's pawns trap it. Back-rank mate!" },
  { div: "68", board: { a8: "bK", e8: "bR", c7: "wN" }, highlight: ["c7", "a8", "e8"],
    ask: "The white knight on c7 attacks the king AND the rook at once. This is called a…",
    options: ["Fork", "Pin", "Castle"], answer: "Fork",
    tip: "A fork attacks two (or more) pieces at the same time." },
  { div: "68", board: { a8: "bK", d5: "bN", g2: "wB" }, highlight: ["g2", "d5", "a8"],
    ask: "The knight can't move because the king is behind it on the same line. This is a…",
    options: ["Pin", "Fork", "Check"], answer: "Pin",
    tip: "A pin freezes a piece because moving it would expose a more valuable piece." },
  { div: "68", board: { a1: "wR", a4: "bK", a8: "bQ" }, highlight: ["a1", "a4", "a8"],
    ask: "The rook checks the king; when the king moves, White grabs the queen behind it. This is a…",
    options: ["Skewer", "Fork", "Stalemate"], answer: "Skewer",
    tip: "A skewer is like a pin, but the more valuable piece is in front." },
  { div: "68", board: { e5: "wP", d5: "bP" }, highlight: ["e5", "d5"],
    ask: "White captures en passant. Which square does the white pawn land on?",
    options: ["d6", "d5", "e6"], answer: "d6",
    tip: "En passant captures to the square the enemy pawn skipped over — here, d6." },
  { div: "68", board: { d1: "wQ", d8: "bR", f8: "bB", b8: "bN" }, highlight: ["d1", "d8", "f8", "b8"],
    ask: "White has a Queen. Black has a Rook, a Bishop and a Knight. Who has more points?",
    options: ["Black", "White", "Equal"], answer: "Black",
    tip: "Black: 5 + 3 + 3 = 11 vs White's Queen = 9. Black is ahead." },
  { div: "68", board: { e8: "bK", a7: "wR", b8: "wR" }, highlight: ["e8", "a7", "b8"],
    ask: "Two rooks vs the lone king. Is the black king checkmated?",
    options: ["Yes", "No"], answer: "Yes",
    tip: "One rook checks on rank 8; the other covers rank 7 so the king can't escape. Ladder mate." },
  { div: "68", board: { d1: "wR", d8: "bQ" }, highlight: ["d1", "d8"],
    ask: "White to move on the open d-file. What's the best move?",
    options: ["Rxd8 (take the queen)", "Rd4", "Ra1"], answer: "Rxd8 (take the queen)",
    tip: "Win the biggest piece you safely can — take the queen!" },
  { div: "68", board: { g8: "bK", f7: "bP" }, highlight: [],
    ask: "In chess notation, what does the “x” mean (as in Rxd8)?",
    options: ["Capture", "Check", "Castle"], answer: "Capture",
    tip: "“x” means a capture; “+” means check; “#” means checkmate." },
  { div: "68", board: { e1: "wK", h1: "wR" }, highlight: ["e1", "h1"],
    ask: "The notation “O-O” means…",
    options: ["Castle kingside", "Checkmate", "A draw"], answer: "Castle kingside",
    tip: "O-O is kingside castling; O-O-O is queenside." },
];

/* Official / recommended practice links (open in a new tab). */
const CHESS_LINKS = [
  { emoji: "🏆", label: "A+ Chess Puzzle (UIL event page)", url: "https://www.uiltexas.org/aplus/events/a-chess-puzzle" },
  { emoji: "📝", label: "A+ Chess Sample Test, Key & Answer Sheet (PDF)", url: "https://www.uiltexas.org/files/academics/aplus/A+_Chess_Sample_Ansswer_Sheet,_Test,_and_Key.pdf" },
  { emoji: "📄", label: "Sample Questions 2016 (PDF)", url: "https://www.uiltexas.org/files/academics/aplus/UIL_Sample_2016.pdf" },
  { emoji: "📚", label: "How to Study for A+ Chess Puzzle (PDF)", url: "https://www.uiltexas.org/files/academics/aplus/Studying_for_Chess_Puzzlenew2016.pdf" },
  { emoji: "🗂️", label: "Previous years' A+ tests", url: "https://www.uiltexas.org/aplus/resources/home" },
  { emoji: "🧩", label: "Kid Chess — puzzles", url: "http://www.kidchess.com/puzzles/puzzles.html" },
  { emoji: "♟️", label: "ChessKid.com", url: "https://www.chesskid.com/" },
  { emoji: "↔️", label: "Learn En Passant (chess.com)", url: "https://www.chess.com/terms/en-passant" },
  { emoji: "🎓", label: "Texas Tech Chess", url: "http://www.depts.ttu.edu/ttuchess/" },
];
